SELECT 
studentbasicinformation.StudentName,
studentbasicinformation.StudentSurname,
studentbasicinformation.StudentRollNo, 
studentbasicinformation.StudentAddress, 
studentsubjectinformation.StudentMarksPercentage,
subjectscholarshipinformation.ScholarshipAmount
FROM 
studentbasicinformation
INNER JOIN studentsubjectinformation
INNER JOIN subjectscholarshipinformation ON 
studentbasicinformation.StudentRollNo = studentsubjectinformation.StudentRollNo AND
studentbasicinformation.StudentRollNo = subjectscholarshipinformation.StudentRollNo
WHERE StudentMarksPercentage = 
(SELECT MAX(StudentMarksPercentage)
FROM StudentSubjectInformation) AND ScholarshipAmount = (SELECT MAX(ScholarshipAmount) 
FROMSubjectScholarshipInformation);